services:
    br_bar.type.account:
        class: BR\BarBundle\Form\Account\AccountType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: account }


    br_bar.type.bar_id:
        class: BR\BarBundle\Form\Bar\BarIdType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: bar_id }

    br_bar.type.user_id:
        class: BR\BarBundle\Form\Auth\UserIdType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: user_id }

    br_bar.type.account_id:
        class: BR\BarBundle\Form\Account\AccountIdType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: account_id }

    br_bar.type.item_id:
        class: BR\BarBundle\Form\Stock\StockItemIdType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: item_id }
