services:
    br_bar.type.bar:
        class: BR\BarBundle\Type\Bar\BarType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: bar }
    br_bar.type.user:
        class: BR\BarBundle\Type\Auth\UserType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: user }
    br_bar.type.account:
        class: BR\BarBundle\Type\Account\AccountType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: account }
    br_bar.type.friend:
        class: BR\BarBundle\Type\Account\FriendType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: friend }
    br_bar.type.item:
        class: BR\BarBundle\Type\Stock\StockItemType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: item }


    br_bar.type.bar_id:
        class: BR\BarBundle\Type\Bar\BarIdType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: bar_id }

    br_bar.type.user_id:
        class: BR\BarBundle\Type\Auth\UserIdType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: user_id }

    br_bar.type.account_id:
        class: BR\BarBundle\Type\Account\AccountIdType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: account_id }

    br_bar.type.friend_id:
        class: BR\BarBundle\Type\Account\FriendIdType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: friend_id }

    br_bar.type.item_id:
        class: BR\BarBundle\Type\Stock\StockItemIdType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: item_id }

