br_bar_root:
    type:     rest
    resource: BR\BarBundle\Controller\DefaultController

br_bar_auth:
    type:     rest
    resource: BR\BarBundle\Controller\AuthController

br_bar_bar:
    type:     rest
    resource: BR\BarBundle\Controller\BarController

br_bar_food:
    type:     rest
    resource: BR\BarBundle\Controller\FoodController

br_bar_transaction:
    type:     rest
    resource: BR\BarBundle\Controller\TransactionController

br_bar_user:
    type:     rest
    resource: BR\BarBundle\Controller\UserController
