parameters:
   br_bar.user_provider.class: BR\BarBundle\Security\UserProvider

services:
   br_bar.user_provider:
       class: %br_bar.user_provider.class%
       arguments: ['@doctrine.orm.entity_manager']
