security:
    encoders:
        BR\BarBundle\Entity\Auth\User: plaintext
            # algorithm: bcrypt
        # Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        users:
            id: br_bar.user_provider


    firewalls:
        main:
            pattern:    ^/
            lexik_jwt:  ~
            stateless:  true
            anonymous:  true

            # form_login:
            #     check_path: ^/[^/]*/login
            #     require_previous_session: false
            #     username_parameter: username
            #     password_parameter: password
            #     success_handler: lexik_jwt_authentication.handler.authentication_success
            #     failure_handler: lexik_jwt_authentication.handler.authentication_failure

        # main:
        #     pattern:    ^/
        #     # stateless:  true
        #     http_basic: ~
        #     # security: true
        #     # anonymous:  true

    # access_control:
    #     - { path: ^/, roles: ROLE_USER}
    #     #, requires_channel: https }


#         login:
#             pattern:  ^/demo/secured/login$
#             security: false

#         secured_area:
#             pattern:    ^/demo/secured/
#             form_login:
#                 check_path: _security_check
#                 login_path: _demo_login
#             logout:
#                 path:   _demo_logout
#                 target: _demo
#             #anonymous: ~
#             #http_basic:
#             #    realm: "Secured Demo Area"

#     providers:
#         in_memory:
#             memory:
#                 users:
#                     user:  { password: userpass, roles: [ 'ROLE_USER' ] }
#                     admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }


#     access_control:
#         #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
