security:
    encoders:
        BR\BarBundle\Entity\Auth\User: plaintext
            # algorithm: bcrypt
        # Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        users:
            id: br_bar.user_provider


    firewalls:
        main:
            pattern:    ^/
            http_basic: ~
            stateless:  true
            anonymous:  true
