security:
    encoders:
        BR\BarBundle\Entity\Auth\User: plaintext
            # algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        users:
            entity: { class: BRBarBundle:Auth\User, property: login }


    firewalls:
        main:
            pattern:    ^/
            stateless:  true
            anonymous:  true
            lexik_jwt:
                create_entry_point: true
                authorization_header:
                    enabled: true
                    prefix:  Bearer
                query_parameter:
                    enabled: true
                    name:    bearer

    # access_control:
    #     - { path: /user, roles: ROLE_USER}
